import { Stack } from "@chakra-ui/react";
import Head from "next/head";
import Navigator from "./Navigator";

const Layout = ({ children }: any) => {
  return (
    <Stack >
      <Head>
        <title>facuariasla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navigator/> */}
      <Stack align='center'>{children}</Stack>
    </Stack>
  );
};

export default Layout;
